/**
 * Derive a single, replayable schema baseline from the live database.
 *
 * The migration history under `supabase/migrations/` stays authoritative and
 * untouched; this file is a *derived* artifact that answers one question —
 * "what shape is the database in right now?" — in a form that can be replayed
 * onto an empty Postgres. It is generated in the cutover freeze window and
 * re-checked afterwards to prove the cutover changed no schema.
 *
 * Run with:
 *   bun run baseline:write    # writes supabase/baseline/*.sql + MANIFEST.json
 *   bun run baseline:check    # regenerates and diffs; non-zero exit on drift
 *
 * Reads the catalogue through `psql`, so the usual PG* environment variables
 * (or PGURL) must point at the database. Only SELECTs are issued.
 */
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dir ?? process.cwd(), "..");
const OUT_DIR = join(ROOT, "supabase/baseline");
const MANIFEST = join(OUT_DIR, "MANIFEST.json");
/** Everything the baseline assumes already exists, rather than creating it. */
const PREREQUISITE_ROLES = ["anon", "authenticated", "service_role"];
/** Schemas the baseline owns. Supabase-managed schemas are prerequisites. */
const OWNED_SCHEMAS = ["public", "private"];
/** psql field/record separators: control chars that never occur in SQL text. */
const FIELD_SEP = "\u001f";
const RECORD_SEP = "\u001e";

function psql(sql: string): string[] {
  // Statements span many lines, so rows are separated by an explicit record
  // separator rather than by newlines.
  const args = [
    "-X",
    "-A",
    "-t",
    "-F",
    "\u001f",
    "-R",
    "\u001e",
    "--no-psqlrc",
    "-v",
    "ON_ERROR_STOP=1",
    "-c",
    sql,
  ];
  if (process.env["PGURL"]) args.unshift(process.env["PGURL"]!);
  const out = execFileSync("psql", args, {
    encoding: "utf8",
    maxBuffer: 64 * 1024 * 1024,
    // Captured, not inherited: optional queries may fail without alarming output.
    stdio: ["ignore", "pipe", "pipe"],
  });
  return out
    .split(RECORD_SEP)
    .map((row) => row.trim())
    .filter((row) => row.length > 0);
}

/** One query returning ready-made SQL statements, one per row. */
function statements(sql: string): string[] {
  return psql(sql).map((s) => s.split(FIELD_SEP).join(""));
}

const schemaList = OWNED_SCHEMAS.map((s) => `'${s}'`).join(",");

const QUERIES: { title: string; sql: string }[] = [
  {
    title: "Extensions",
    sql: `select format('create extension if not exists %I with schema %I;', e.extname, n.nspname)
          from pg_extension e join pg_namespace n on n.oid = e.extnamespace
          where e.extname <> 'plpgsql' order by e.extname`,
  },
  {
    title: "Schemas",
    sql: `select format('create schema if not exists %I;', nspname)
          from pg_namespace where nspname in (${schemaList}) and nspname <> 'public' order by nspname`,
  },
  {
    title: "Enum types",
    sql: `select format('create type %I.%I as enum (%s);', n.nspname, t.typname,
                 (select string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder)
                    from pg_enum e where e.enumtypid = t.oid))
          from pg_type t join pg_namespace n on n.oid = t.typnamespace
          where t.typtype = 'e' and n.nspname in (${schemaList})
          order by n.nspname, t.typname`,
  },
  {
    title: "Functions",
    sql: `select pg_get_functiondef(p.oid) || ';'
          from pg_proc p join pg_namespace n on n.oid = p.pronamespace
          where n.nspname in (${schemaList}) and p.prokind = 'f'
            and not exists (select 1 from pg_depend d
                            where d.objid = p.oid and d.deptype = 'e')
          order by n.nspname, p.proname, p.oid`,
  },
  {
    title: "Tables",
    sql: `select format('create table if not exists %I.%I (%s%s);', n.nspname, c.relname,
                 chr(10) || '  ',
                 (select string_agg(
                           format('%I %s%s%s', a.attname, format_type(a.atttypid, a.atttypmod),
                                  case when a.attidentity <> '' then ' generated by default as identity' else '' end,
                                  case when a.attnotnull then ' not null' else '' end)
                           || case
                                when a.attgenerated <> ''
                                  then format(' generated always as (%s) stored',
                                              pg_get_expr(ad.adbin, ad.adrelid))
                                else coalesce(' default ' || pg_get_expr(ad.adbin, ad.adrelid), '')
                              end,
                           ',' || chr(10) || '  ' order by a.attnum)
                    from pg_attribute a
                    left join pg_attrdef ad on ad.adrelid = a.attrelid and ad.adnum = a.attnum
                   where a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped))
          from pg_class c join pg_namespace n on n.oid = c.relnamespace
          where c.relkind = 'r' and n.nspname in (${schemaList})
          order by n.nspname, c.relname`,
  },
  {
    title: "Primary keys and unique constraints",
    sql: `select format('alter table %I.%I add constraint %I %s;', n.nspname, c.relname, con.conname,
                        pg_get_constraintdef(con.oid))
          from pg_constraint con
          join pg_class c on c.oid = con.conrelid
          join pg_namespace n on n.oid = c.relnamespace
          where con.contype in ('p','u') and n.nspname in (${schemaList})
          order by con.contype desc, n.nspname, c.relname, con.conname`,
  },
  {
    title: "Check constraints",
    sql: `select format('alter table %I.%I add constraint %I %s;', n.nspname, c.relname, con.conname,
                        pg_get_constraintdef(con.oid))
          from pg_constraint con
          join pg_class c on c.oid = con.conrelid
          join pg_namespace n on n.oid = c.relnamespace
          where con.contype = 'c' and n.nspname in (${schemaList})
          order by n.nspname, c.relname, con.conname`,
  },
  {
    title: "Foreign keys",
    sql: `select format('alter table %I.%I add constraint %I %s;', n.nspname, c.relname, con.conname,
                        pg_get_constraintdef(con.oid))
          from pg_constraint con
          join pg_class c on c.oid = con.conrelid
          join pg_namespace n on n.oid = c.relnamespace
          where con.contype = 'f' and n.nspname in (${schemaList})
          order by n.nspname, c.relname, con.conname`,
  },
  {
    title: "Indexes",
    sql: `select pg_get_indexdef(i.indexrelid) || ';'
          from pg_index i
          join pg_class c on c.oid = i.indrelid
          join pg_class ic on ic.oid = i.indexrelid
          join pg_namespace n on n.oid = c.relnamespace
          where n.nspname in (${schemaList})
            and not exists (select 1 from pg_constraint con where con.conindid = i.indexrelid)
          order by n.nspname, c.relname, ic.relname`,
  },
  {
    title: "Views",
    sql: `select format('create or replace view %I.%I%s as%s%s', n.nspname, c.relname,
                 case when c.reloptions is null then ''
                      else format(' with (%s)', array_to_string(c.reloptions, ', ')) end,
                 chr(10), pg_get_viewdef(c.oid, true))
          from pg_class c join pg_namespace n on n.oid = c.relnamespace
          where c.relkind = 'v' and n.nspname in (${schemaList})
          order by n.nspname, c.relname`,
  },
  {
    title: "Triggers",
    sql: `select pg_get_triggerdef(t.oid) || ';'
          from pg_trigger t
          join pg_class c on c.oid = t.tgrelid
          join pg_namespace n on n.oid = c.relnamespace
          where not t.tgisinternal and n.nspname in (${schemaList})
          order by n.nspname, c.relname, t.tgname`,
  },
  {
    title: "Row level security",
    sql: `select format('alter table %I.%I enable row level security;', n.nspname, c.relname)
          from pg_class c join pg_namespace n on n.oid = c.relnamespace
          where c.relkind = 'r' and c.relrowsecurity and n.nspname in (${schemaList})
          order by n.nspname, c.relname`,
  },
  {
    title: "Policies",
    sql: `select format('create policy %I on %I.%I as %s for %s to %s%s%s;',
                 p.polname, n.nspname, c.relname,
                 case when p.polpermissive then 'permissive' else 'restrictive' end,
                 case p.polcmd when 'r' then 'select' when 'a' then 'insert'
                               when 'w' then 'update' when 'd' then 'delete' else 'all' end,
                 coalesce((select string_agg(quote_ident(r.rolname), ', ' order by r.rolname)
                             from pg_roles r where r.oid = any(p.polroles)), 'public'),
                 -- format() renders NULL as an empty string, so the optional
                 -- clauses are built with case, not coalesce.
                 case when p.polqual is null then ''
                      else format(' using (%s)', pg_get_expr(p.polqual, p.polrelid)) end,
                 case when p.polwithcheck is null then ''
                      else format(' with check (%s)', pg_get_expr(p.polwithcheck, p.polrelid)) end)
          from pg_policy p
          join pg_class c on c.oid = p.polrelid
          join pg_namespace n on n.oid = c.relnamespace
          where n.nspname in (${schemaList})
          order by n.nspname, c.relname, p.polname`,
  },
  {
    title: "Schema and function grants",
    sql: `select format('grant usage on schema %I to %I;', n.nspname, r.rolname)
          from pg_namespace n
          cross join (select rolname from pg_roles
                       where rolname in (${PREREQUISITE_ROLES.map((r) => `'${r}'`).join(",")})) r
          where n.nspname in (${schemaList})
            and has_schema_privilege(r.rolname, n.nspname, 'USAGE')
          order by n.nspname, r.rolname`,
  },
  {
    title: "Table grants",
    sql: `with roles as (select rolname from pg_roles
                          where rolname in (${PREREQUISITE_ROLES.map((r) => `'${r}'`).join(",")})),
               privs as (select unnest(array['SELECT','INSERT','UPDATE','DELETE']) as p)
          select format('grant %s on %I.%I to %I;',
                        string_agg(privs.p, ', ' order by privs.p), n.nspname, c.relname, roles.rolname)
          from pg_class c
          join pg_namespace n on n.oid = c.relnamespace
          cross join roles cross join privs
          where c.relkind in ('r','v') and n.nspname in (${schemaList})
            and has_table_privilege(roles.rolname, c.oid, privs.p)
          group by n.nspname, c.relname, roles.rolname
          order by n.nspname, c.relname, roles.rolname`,
  },
  {
    title: "Column grants",
    sql: `with roles as (select rolname from pg_roles
                          where rolname in (${PREREQUISITE_ROLES.map((r) => `'${r}'`).join(",")}))
          select format('grant select (%s) on %I.%I to %I;',
                        string_agg(quote_ident(a.attname), ', ' order by a.attnum),
                        n.nspname, c.relname, roles.rolname)
          from pg_class c
          join pg_namespace n on n.oid = c.relnamespace
          join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
          cross join roles
          where c.relkind = 'r' and n.nspname in (${schemaList})
            -- Column grants only matter where the whole table is NOT granted.
            and not has_table_privilege(roles.rolname, c.oid, 'SELECT')
            and has_column_privilege(roles.rolname, c.oid, a.attnum, 'SELECT')
          group by n.nspname, c.relname, roles.rolname
          order by n.nspname, c.relname, roles.rolname`,
  },
  {
    title: "Storage buckets",
    sql: `select format('insert into storage.buckets (id, name, public) values (%L, %L, %L) on conflict (id) do nothing;',
                        id, name, public)
          from storage.buckets order by id`,
  },
  {
    title: "Storage policies",
    sql: `select format('create policy %I on storage.objects as %s for %s to %s%s%s;',
                 p.polname,
                 case when p.polpermissive then 'permissive' else 'restrictive' end,
                 case p.polcmd when 'r' then 'select' when 'a' then 'insert'
                               when 'w' then 'update' when 'd' then 'delete' else 'all' end,
                 coalesce((select string_agg(quote_ident(r.rolname), ', ' order by r.rolname)
                             from pg_roles r where r.oid = any(p.polroles)), 'public'),
                 -- format() renders NULL as an empty string, so the optional
                 -- clauses are built with case, not coalesce.
                 case when p.polqual is null then ''
                      else format(' using (%s)', pg_get_expr(p.polqual, p.polrelid)) end,
                 case when p.polwithcheck is null then ''
                      else format(' with check (%s)', pg_get_expr(p.polwithcheck, p.polrelid)) end)
          from pg_policy p
          where p.polrelid = 'storage.objects'::regclass
          order by p.polname`,
  },
];

const HEADER = `-- ============================================================================
-- Schema baseline — The Switzerland Chapter of ICF
--
-- DERIVED ARTIFACT. Generated by \`bun run baseline:write\` from the live
-- catalogue. Never hand-edit: regenerate instead. The authoritative history
-- remains the migration files under supabase/migrations/.
--
-- This file contains SCHEMA ONLY plus storage bucket definitions. It holds no
-- member data, no CMS content and no vocabulary rows, so it is NOT a backup.
--
-- Prerequisites the target database must already provide (Supabase does):
--   * roles: ${PREREQUISITE_ROLES.join(", ")}
--   * schemas: auth, storage, extensions, vault, realtime, cron, net
--   * auth.users and storage.objects
--   * the trigger auth.users -> public.handle_new_user() is NOT recreated here,
--     because the auth schema is Supabase-managed; re-add it deliberately.
--   * cron.job entries are not readable by an unprivileged role and are not
--     included; re-create the scheduled jobs from docs/operations-and-go-live.md.
-- ============================================================================

set statement_timeout = 0;
set client_min_messages = warning;
-- Functions are emitted before the tables and views they reference (pg_dump does
-- the same), so body validation must be off during replay.
set check_function_bodies = false;
set search_path = public, extensions;
`;

function build(): { sql: string; counts: Record<string, number> } {
  const parts: string[] = [HEADER];
  const counts: Record<string, number> = {};
  for (const { title, sql } of QUERIES) {
    const rows = statements(sql);
    counts[title] = rows.length;
    if (rows.length === 0) continue;
    parts.push(`\n-- ---------------------------------------------------------------------------
-- ${title} (${rows.length})
-- ---------------------------------------------------------------------------\n`);
    parts.push(rows.join("\n\n"));
    parts.push("");
  }
  return {
    sql:
      parts
        .join("\n")
        .replace(/\n{3,}/g, "\n\n")
        .trimEnd() + "\n",
    counts,
  };
}

function ledgerVersion(): string {
  // Readable by the migration role only; unprivileged runs still produce a baseline.
  try {
    const [version] = psql("select max(version) from supabase_migrations.schema_migrations");
    return version ?? "unknown";
  } catch {
    return "unreadable";
  }
}

function existingBaseline(): { file: string; sql: string } | null {
  if (!existsSync(OUT_DIR)) return null;
  const files = readdirSync(OUT_DIR)
    .filter((f) => f.endsWith("_baseline.sql"))
    .sort();
  const latest = files.at(-1);
  if (!latest) return null;
  return { file: latest, sql: readFileSync(join(OUT_DIR, latest), "utf8") };
}

/** Ignores the generation timestamp in the header, which always differs. */
function comparable(sql: string): string {
  return sql.replace(/^-- generated at .*$/gm, "");
}

const mode = process.argv[2] ?? "--check";
const { sql, counts } = build();
const version = ledgerVersion();
const stamp = new Date().toISOString().replace(/[-:]/g, "").replace(/\..+/, "").replace("T", "");
const body = sql.replace(HEADER, `${HEADER}\n-- generated at ${new Date().toISOString()}\n`);

if (mode === "--write") {
  mkdirSync(OUT_DIR, { recursive: true });
  const name = `${stamp}_baseline.sql`;
  writeFileSync(join(OUT_DIR, name), body);
  writeFileSync(
    MANIFEST,
    JSON.stringify(
      {
        file: name,
        generated_at: new Date().toISOString(),
        migration_ledger_version: version,
        counts,
      },
      null,
      2,
    ) + "\n",
  );
  console.log(`Wrote supabase/baseline/${name}`);
  for (const [title, n] of Object.entries(counts)) console.log(`  ${title.padEnd(34)} ${n}`);
  process.exit(0);
}

const existing = existingBaseline();
if (!existing) {
  console.error("No baseline committed yet. Run: bun run baseline:write");
  process.exit(1);
}
if (comparable(existing.sql) !== comparable(body)) {
  console.error(`DRIFT: the database no longer matches supabase/baseline/${existing.file}.`);
  console.error("Regenerate with `bun run baseline:write` and review the diff before committing.");
  process.exit(1);
}
console.log(`No drift: database matches supabase/baseline/${existing.file} (ledger ${version}).`);
