/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as MemberRouteRouteImport } from './routes/_member/route'
import { Route as StaffRouteRouteImport } from './routes/_staff/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EuropePulseRouteImport } from './routes/europe-pulse'
import { Route as FindACoachRouteImport } from './routes/find-a-coach'
import { Route as ForCoachesRouteImport } from './routes/for-coaches'
import { Route as ForOrganisationsRouteImport } from './routes/for-organisations'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as NoAccessRouteImport } from './routes/no-access'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StaffSignInRouteImport } from './routes/staff-sign-in'
import { Route as TeamRouteImport } from './routes/team'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleAboutRouteImport } from './routes/$locale/about'
import { Route as LocaleEuropePulseRouteImport } from './routes/$locale/europe-pulse'
import { Route as LocaleFindACoachRouteImport } from './routes/$locale/find-a-coach'
import { Route as LocaleForCoachesRouteImport } from './routes/$locale/for-coaches'
import { Route as LocaleForOrganisationsRouteImport } from './routes/$locale/for-organisations'
import { Route as LocaleGovernanceRouteImport } from './routes/$locale/governance'
import { Route as LocaleImprintRouteImport } from './routes/$locale/imprint'
import { Route as LocaleInsightsRouteImport } from './routes/$locale/insights'
import { Route as LocalePrivacyRouteImport } from './routes/$locale/privacy'
import { Route as LocaleTeamRouteImport } from './routes/$locale/team'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as MemberMemberRouteImport } from './routes/_member/member'
import { Route as MemberMyProfileRouteImport } from './routes/_member/my-profile'
import { Route as MemberVolunteerChatRouteImport } from './routes/_member/volunteer-chat'
import { Route as StaffArticlesRouteImport } from './routes/_staff/articles'
import { Route as StaffCoachFinderRouteImport } from './routes/_staff/coach-finder'
import { Route as StaffIntegrationRouteImport } from './routes/_staff/integration'
import { Route as StaffOperationalStructureRouteImport } from './routes/_staff/operational-structure'
import { Route as StaffRolesRouteImport } from './routes/_staff/roles'
import { Route as StaffVocabulariesRouteImport } from './routes/_staff/vocabularies'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ClaimIndexRouteImport } from './routes/claim.index'
import { Route as ClaimTokenRouteImport } from './routes/claim.$token'
import { Route as CoachProfileIdRouteImport } from './routes/coach.$profileId'
import { Route as CommunitiesIndexRouteImport } from './routes/communities.index'
import { Route as CommunitiesSlugRouteImport } from './routes/communities.$slug'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as FormTokenRouteImport } from './routes/form.$token'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsIdRouteImport } from './routes/insights.$id'
import { Route as TicketTokenRouteImport } from './routes/ticket.$token'
import { Route as LocaleCoachProfileIdRouteImport } from './routes/$locale/coach.$profileId'
import { Route as LocaleCommunitiesIndexRouteImport } from './routes/$locale/communities.index'
import { Route as LocaleCommunitiesSlugRouteImport } from './routes/$locale/communities.$slug'
import { Route as LocaleEventsIndexRouteImport } from './routes/$locale/events.index'
import { Route as LocaleEventsSlugRouteImport } from './routes/$locale/events.$slug'
import { Route as LocaleInsightsIndexRouteImport } from './routes/$locale/insights.index'
import { Route as LocaleInsightsIdRouteImport } from './routes/$locale/insights.$id'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as StaffArticlesIndexRouteImport } from './routes/_staff/articles.index'
import { Route as StaffArticlesIdRouteImport } from './routes/_staff/articles.$id'
import { Route as StaffArticlesCategoriesRouteImport } from './routes/_staff/articles.categories'
import { Route as StaffArticlesNewRouteImport } from './routes/_staff/articles.new'
import { Route as StaffManageChatInsightsRouteImport } from './routes/_staff/manage.chat-insights'
import { Route as StaffManageEuropePulseRouteImport } from './routes/_staff/manage.europe-pulse'
import { Route as StaffManageGovernanceRouteImport } from './routes/_staff/manage.governance'
import { Route as StaffManageKnowledgeRouteImport } from './routes/_staff/manage.knowledge'
import { Route as StaffManageLiveChatRouteImport } from './routes/_staff/manage.live-chat'
import { Route as StaffMembersIndexRouteImport } from './routes/_staff/members.index'
import { Route as StaffMembersIdRouteImport } from './routes/_staff/members.$id'
import { Route as ApiPublicChatSignalRouteImport } from './routes/api/public/chat-signal'
import { Route as ApiPublicEuropePulseScanRouteImport } from './routes/api/public/europe-pulse-scan'
import { Route as ApiPublicEventRemindersRouteImport } from './routes/api/public/event-reminders'
import { Route as ApiPublicLiveChatRouteImport } from './routes/api/public/live-chat'
import { Route as ApiPublicLiveChatPurgeRouteImport } from './routes/api/public/live-chat-purge'
import { Route as ApiPublicMemberSyncRouteImport } from './routes/api/public/member-sync'
import { Route as StaffManageEventsIndexRouteImport } from './routes/_staff/manage.events.index'
import { Route as StaffManageEventsIdRouteImport } from './routes/_staff/manage.events.$id'
import { Route as ApiPublicCalendarFileRouteImport } from './routes/api/public/calendar.$file'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicTicketQrTokenRouteImport } from './routes/api/public/ticket-qr.$token'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as StaffManageEventsIdCceRouteImport } from './routes/_staff/manage.events.$id_.cce'
import { Route as StaffManageEventsIdCheckInRouteImport } from './routes/_staff/manage.events.$id_.check-in'
import { Route as StaffManageEventsIdReportingRouteImport } from './routes/_staff/manage.events.$id_.reporting'
import { Route as StaffManageEventsIdFormsFormIdRouteImport } from './routes/_staff/manage.events.$id_.forms.$formId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRouteRoute = MemberRouteRouteImport.update({
  id: '/_member',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRouteRoute = StaffRouteRouteImport.update({
  id: '/_staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EuropePulseRoute = EuropePulseRouteImport.update({
  id: '/europe-pulse',
  path: '/europe-pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const FindACoachRoute = FindACoachRouteImport.update({
  id: '/find-a-coach',
  path: '/find-a-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCoachesRoute = ForCoachesRouteImport.update({
  id: '/for-coaches',
  path: '/for-coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const ForOrganisationsRoute = ForOrganisationsRouteImport.update({
  id: '/for-organisations',
  path: '/for-organisations',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSignInRoute = StaffSignInRouteImport.update({
  id: '/staff-sign-in',
  path: '/staff-sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleEuropePulseRoute = LocaleEuropePulseRouteImport.update({
  id: '/europe-pulse',
  path: '/europe-pulse',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleFindACoachRoute = LocaleFindACoachRouteImport.update({
  id: '/find-a-coach',
  path: '/find-a-coach',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleForCoachesRoute = LocaleForCoachesRouteImport.update({
  id: '/for-coaches',
  path: '/for-coaches',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleForOrganisationsRoute = LocaleForOrganisationsRouteImport.update({
  id: '/for-organisations',
  path: '/for-organisations',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleGovernanceRoute = LocaleGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleImprintRoute = LocaleImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleInsightsRoute = LocaleInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocalePrivacyRoute = LocalePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleTeamRoute = LocaleTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const MemberMemberRoute = MemberMemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => MemberRouteRoute,
} as any)
const MemberMyProfileRoute = MemberMyProfileRouteImport.update({
  id: '/my-profile',
  path: '/my-profile',
  getParentRoute: () => MemberRouteRoute,
} as any)
const MemberVolunteerChatRoute = MemberVolunteerChatRouteImport.update({
  id: '/volunteer-chat',
  path: '/volunteer-chat',
  getParentRoute: () => MemberRouteRoute,
} as any)
const StaffArticlesRoute = StaffArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffCoachFinderRoute = StaffCoachFinderRouteImport.update({
  id: '/coach-finder',
  path: '/coach-finder',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffIntegrationRoute = StaffIntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffOperationalStructureRoute =
  StaffOperationalStructureRouteImport.update({
    id: '/operational-structure',
    path: '/operational-structure',
    getParentRoute: () => StaffRouteRoute,
  } as any)
const StaffRolesRoute = StaffRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffVocabulariesRoute = StaffVocabulariesRouteImport.update({
  id: '/vocabularies',
  path: '/vocabularies',
  getParentRoute: () => StaffRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ClaimIndexRoute = ClaimIndexRouteImport.update({
  id: '/claim/',
  path: '/claim/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimTokenRoute = ClaimTokenRouteImport.update({
  id: '/claim/$token',
  path: '/claim/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachProfileIdRoute = CoachProfileIdRouteImport.update({
  id: '/coach/$profileId',
  path: '/coach/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesIndexRoute = CommunitiesIndexRouteImport.update({
  id: '/communities/',
  path: '/communities/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesSlugRoute = CommunitiesSlugRouteImport.update({
  id: '/communities/$slug',
  path: '/communities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FormTokenRoute = FormTokenRouteImport.update({
  id: '/form/$token',
  path: '/form/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InsightsRoute,
} as any)
const InsightsIdRoute = InsightsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InsightsRoute,
} as any)
const TicketTokenRoute = TicketTokenRouteImport.update({
  id: '/ticket/$token',
  path: '/ticket/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleCoachProfileIdRoute = LocaleCoachProfileIdRouteImport.update({
  id: '/coach/$profileId',
  path: '/coach/$profileId',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleCommunitiesIndexRoute = LocaleCommunitiesIndexRouteImport.update({
  id: '/communities/',
  path: '/communities/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleCommunitiesSlugRoute = LocaleCommunitiesSlugRouteImport.update({
  id: '/communities/$slug',
  path: '/communities/$slug',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleEventsIndexRoute = LocaleEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleEventsSlugRoute = LocaleEventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleInsightsIndexRoute = LocaleInsightsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleInsightsRoute,
} as any)
const LocaleInsightsIdRoute = LocaleInsightsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LocaleInsightsRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const StaffArticlesIndexRoute = StaffArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffArticlesRoute,
} as any)
const StaffArticlesIdRoute = StaffArticlesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaffArticlesRoute,
} as any)
const StaffArticlesCategoriesRoute = StaffArticlesCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => StaffArticlesRoute,
} as any)
const StaffArticlesNewRoute = StaffArticlesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StaffArticlesRoute,
} as any)
const StaffManageChatInsightsRoute = StaffManageChatInsightsRouteImport.update({
  id: '/manage/chat-insights',
  path: '/manage/chat-insights',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffManageEuropePulseRoute = StaffManageEuropePulseRouteImport.update({
  id: '/manage/europe-pulse',
  path: '/manage/europe-pulse',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffManageGovernanceRoute = StaffManageGovernanceRouteImport.update({
  id: '/manage/governance',
  path: '/manage/governance',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffManageKnowledgeRoute = StaffManageKnowledgeRouteImport.update({
  id: '/manage/knowledge',
  path: '/manage/knowledge',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffManageLiveChatRoute = StaffManageLiveChatRouteImport.update({
  id: '/manage/live-chat',
  path: '/manage/live-chat',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffMembersIndexRoute = StaffMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffMembersIdRoute = StaffMembersIdRouteImport.update({
  id: '/members/$id',
  path: '/members/$id',
  getParentRoute: () => StaffRouteRoute,
} as any)
const ApiPublicChatSignalRoute = ApiPublicChatSignalRouteImport.update({
  id: '/api/public/chat-signal',
  path: '/api/public/chat-signal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEuropePulseScanRoute =
  ApiPublicEuropePulseScanRouteImport.update({
    id: '/api/public/europe-pulse-scan',
    path: '/api/public/europe-pulse-scan',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEventRemindersRoute = ApiPublicEventRemindersRouteImport.update({
  id: '/api/public/event-reminders',
  path: '/api/public/event-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLiveChatRoute = ApiPublicLiveChatRouteImport.update({
  id: '/api/public/live-chat',
  path: '/api/public/live-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLiveChatPurgeRoute = ApiPublicLiveChatPurgeRouteImport.update({
  id: '/api/public/live-chat-purge',
  path: '/api/public/live-chat-purge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMemberSyncRoute = ApiPublicMemberSyncRouteImport.update({
  id: '/api/public/member-sync',
  path: '/api/public/member-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffManageEventsIndexRoute = StaffManageEventsIndexRouteImport.update({
  id: '/manage/events/',
  path: '/manage/events/',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffManageEventsIdRoute = StaffManageEventsIdRouteImport.update({
  id: '/manage/events/$id',
  path: '/manage/events/$id',
  getParentRoute: () => StaffRouteRoute,
} as any)
const ApiPublicCalendarFileRoute = ApiPublicCalendarFileRouteImport.update({
  id: '/api/public/calendar/$file',
  path: '/api/public/calendar/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTicketQrTokenRoute = ApiPublicTicketQrTokenRouteImport.update({
  id: '/api/public/ticket-qr/$token',
  path: '/api/public/ticket-qr/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const StaffManageEventsIdCceRoute = StaffManageEventsIdCceRouteImport.update({
  id: '/manage/events/$id_/cce',
  path: '/manage/events/$id/cce',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffManageEventsIdCheckInRoute =
  StaffManageEventsIdCheckInRouteImport.update({
    id: '/manage/events/$id_/check-in',
    path: '/manage/events/$id/check-in',
    getParentRoute: () => StaffRouteRoute,
  } as any)
const StaffManageEventsIdReportingRoute =
  StaffManageEventsIdReportingRouteImport.update({
    id: '/manage/events/$id_/reporting',
    path: '/manage/events/$id/reporting',
    getParentRoute: () => StaffRouteRoute,
  } as any)
const StaffManageEventsIdFormsFormIdRoute =
  StaffManageEventsIdFormsFormIdRouteImport.update({
    id: '/manage/events/$id_/forms/$formId',
    path: '/manage/events/$id/forms/$formId',
    getParentRoute: () => StaffRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/europe-pulse': typeof EuropePulseRoute
  '/find-a-coach': typeof FindACoachRoute
  '/for-coaches': typeof ForCoachesRoute
  '/for-organisations': typeof ForOrganisationsRoute
  '/governance': typeof GovernanceRoute
  '/imprint': typeof ImprintRoute
  '/insights': typeof InsightsRouteWithChildren
  '/mcp': typeof McpRoute
  '/no-access': typeof NoAccessRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff-sign-in': typeof StaffSignInRoute
  '/team': typeof TeamRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/europe-pulse': typeof LocaleEuropePulseRoute
  '/$locale/find-a-coach': typeof LocaleFindACoachRoute
  '/$locale/for-coaches': typeof LocaleForCoachesRoute
  '/$locale/for-organisations': typeof LocaleForOrganisationsRoute
  '/$locale/governance': typeof LocaleGovernanceRoute
  '/$locale/imprint': typeof LocaleImprintRoute
  '/$locale/insights': typeof LocaleInsightsRouteWithChildren
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/team': typeof LocaleTeamRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/member': typeof MemberMemberRoute
  '/my-profile': typeof MemberMyProfileRoute
  '/volunteer-chat': typeof MemberVolunteerChatRoute
  '/articles': typeof StaffArticlesRouteWithChildren
  '/coach-finder': typeof StaffCoachFinderRoute
  '/integration': typeof StaffIntegrationRoute
  '/operational-structure': typeof StaffOperationalStructureRoute
  '/roles': typeof StaffRolesRoute
  '/vocabularies': typeof StaffVocabulariesRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/coach/$profileId': typeof CoachProfileIdRoute
  '/communities/$slug': typeof CommunitiesSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/form/$token': typeof FormTokenRoute
  '/insights/$id': typeof InsightsIdRoute
  '/ticket/$token': typeof TicketTokenRoute
  '/$locale/': typeof LocaleIndexRoute
  '/claim/': typeof ClaimIndexRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/events/': typeof EventsIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/$locale/coach/$profileId': typeof LocaleCoachProfileIdRoute
  '/$locale/communities/$slug': typeof LocaleCommunitiesSlugRoute
  '/$locale/events/$slug': typeof LocaleEventsSlugRoute
  '/$locale/insights/$id': typeof LocaleInsightsIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/articles/$id': typeof StaffArticlesIdRoute
  '/articles/categories': typeof StaffArticlesCategoriesRoute
  '/articles/new': typeof StaffArticlesNewRoute
  '/manage/chat-insights': typeof StaffManageChatInsightsRoute
  '/manage/europe-pulse': typeof StaffManageEuropePulseRoute
  '/manage/governance': typeof StaffManageGovernanceRoute
  '/manage/knowledge': typeof StaffManageKnowledgeRoute
  '/manage/live-chat': typeof StaffManageLiveChatRoute
  '/members/$id': typeof StaffMembersIdRoute
  '/api/public/chat-signal': typeof ApiPublicChatSignalRoute
  '/api/public/europe-pulse-scan': typeof ApiPublicEuropePulseScanRoute
  '/api/public/event-reminders': typeof ApiPublicEventRemindersRoute
  '/api/public/live-chat': typeof ApiPublicLiveChatRoute
  '/api/public/live-chat-purge': typeof ApiPublicLiveChatPurgeRoute
  '/api/public/member-sync': typeof ApiPublicMemberSyncRoute
  '/$locale/communities/': typeof LocaleCommunitiesIndexRoute
  '/$locale/events/': typeof LocaleEventsIndexRoute
  '/$locale/insights/': typeof LocaleInsightsIndexRoute
  '/articles/': typeof StaffArticlesIndexRoute
  '/members/': typeof StaffMembersIndexRoute
  '/manage/events/$id': typeof StaffManageEventsIdRoute
  '/api/public/calendar/$file': typeof ApiPublicCalendarFileRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/ticket-qr/$token': typeof ApiPublicTicketQrTokenRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/manage/events/': typeof StaffManageEventsIndexRoute
  '/manage/events/$id/cce': typeof StaffManageEventsIdCceRoute
  '/manage/events/$id/check-in': typeof StaffManageEventsIdCheckInRoute
  '/manage/events/$id/reporting': typeof StaffManageEventsIdReportingRoute
  '/manage/events/$id/forms/$formId': typeof StaffManageEventsIdFormsFormIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/europe-pulse': typeof EuropePulseRoute
  '/find-a-coach': typeof FindACoachRoute
  '/for-coaches': typeof ForCoachesRoute
  '/for-organisations': typeof ForOrganisationsRoute
  '/governance': typeof GovernanceRoute
  '/imprint': typeof ImprintRoute
  '/mcp': typeof McpRoute
  '/no-access': typeof NoAccessRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff-sign-in': typeof StaffSignInRoute
  '/team': typeof TeamRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/europe-pulse': typeof LocaleEuropePulseRoute
  '/$locale/find-a-coach': typeof LocaleFindACoachRoute
  '/$locale/for-coaches': typeof LocaleForCoachesRoute
  '/$locale/for-organisations': typeof LocaleForOrganisationsRoute
  '/$locale/governance': typeof LocaleGovernanceRoute
  '/$locale/imprint': typeof LocaleImprintRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/team': typeof LocaleTeamRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/member': typeof MemberMemberRoute
  '/my-profile': typeof MemberMyProfileRoute
  '/volunteer-chat': typeof MemberVolunteerChatRoute
  '/coach-finder': typeof StaffCoachFinderRoute
  '/integration': typeof StaffIntegrationRoute
  '/operational-structure': typeof StaffOperationalStructureRoute
  '/roles': typeof StaffRolesRoute
  '/vocabularies': typeof StaffVocabulariesRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/coach/$profileId': typeof CoachProfileIdRoute
  '/communities/$slug': typeof CommunitiesSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/form/$token': typeof FormTokenRoute
  '/insights/$id': typeof InsightsIdRoute
  '/ticket/$token': typeof TicketTokenRoute
  '/$locale': typeof LocaleIndexRoute
  '/claim': typeof ClaimIndexRoute
  '/communities': typeof CommunitiesIndexRoute
  '/events': typeof EventsIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/$locale/coach/$profileId': typeof LocaleCoachProfileIdRoute
  '/$locale/communities/$slug': typeof LocaleCommunitiesSlugRoute
  '/$locale/events/$slug': typeof LocaleEventsSlugRoute
  '/$locale/insights/$id': typeof LocaleInsightsIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/articles/$id': typeof StaffArticlesIdRoute
  '/articles/categories': typeof StaffArticlesCategoriesRoute
  '/articles/new': typeof StaffArticlesNewRoute
  '/manage/chat-insights': typeof StaffManageChatInsightsRoute
  '/manage/europe-pulse': typeof StaffManageEuropePulseRoute
  '/manage/governance': typeof StaffManageGovernanceRoute
  '/manage/knowledge': typeof StaffManageKnowledgeRoute
  '/manage/live-chat': typeof StaffManageLiveChatRoute
  '/members/$id': typeof StaffMembersIdRoute
  '/api/public/chat-signal': typeof ApiPublicChatSignalRoute
  '/api/public/europe-pulse-scan': typeof ApiPublicEuropePulseScanRoute
  '/api/public/event-reminders': typeof ApiPublicEventRemindersRoute
  '/api/public/live-chat': typeof ApiPublicLiveChatRoute
  '/api/public/live-chat-purge': typeof ApiPublicLiveChatPurgeRoute
  '/api/public/member-sync': typeof ApiPublicMemberSyncRoute
  '/$locale/communities': typeof LocaleCommunitiesIndexRoute
  '/$locale/events': typeof LocaleEventsIndexRoute
  '/$locale/insights': typeof LocaleInsightsIndexRoute
  '/articles': typeof StaffArticlesIndexRoute
  '/members': typeof StaffMembersIndexRoute
  '/manage/events/$id': typeof StaffManageEventsIdRoute
  '/api/public/calendar/$file': typeof ApiPublicCalendarFileRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/ticket-qr/$token': typeof ApiPublicTicketQrTokenRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/manage/events': typeof StaffManageEventsIndexRoute
  '/manage/events/$id/cce': typeof StaffManageEventsIdCceRoute
  '/manage/events/$id/check-in': typeof StaffManageEventsIdCheckInRoute
  '/manage/events/$id/reporting': typeof StaffManageEventsIdReportingRoute
  '/manage/events/$id/forms/$formId': typeof StaffManageEventsIdFormsFormIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/_member': typeof MemberRouteRouteWithChildren
  '/_staff': typeof StaffRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/europe-pulse': typeof EuropePulseRoute
  '/find-a-coach': typeof FindACoachRoute
  '/for-coaches': typeof ForCoachesRoute
  '/for-organisations': typeof ForOrganisationsRoute
  '/governance': typeof GovernanceRoute
  '/imprint': typeof ImprintRoute
  '/insights': typeof InsightsRouteWithChildren
  '/mcp': typeof McpRoute
  '/no-access': typeof NoAccessRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff-sign-in': typeof StaffSignInRoute
  '/team': typeof TeamRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/europe-pulse': typeof LocaleEuropePulseRoute
  '/$locale/find-a-coach': typeof LocaleFindACoachRoute
  '/$locale/for-coaches': typeof LocaleForCoachesRoute
  '/$locale/for-organisations': typeof LocaleForOrganisationsRoute
  '/$locale/governance': typeof LocaleGovernanceRoute
  '/$locale/imprint': typeof LocaleImprintRoute
  '/$locale/insights': typeof LocaleInsightsRouteWithChildren
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/team': typeof LocaleTeamRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_member/member': typeof MemberMemberRoute
  '/_member/my-profile': typeof MemberMyProfileRoute
  '/_member/volunteer-chat': typeof MemberVolunteerChatRoute
  '/_staff/articles': typeof StaffArticlesRouteWithChildren
  '/_staff/coach-finder': typeof StaffCoachFinderRoute
  '/_staff/integration': typeof StaffIntegrationRoute
  '/_staff/operational-structure': typeof StaffOperationalStructureRoute
  '/_staff/roles': typeof StaffRolesRoute
  '/_staff/vocabularies': typeof StaffVocabulariesRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/coach/$profileId': typeof CoachProfileIdRoute
  '/communities/$slug': typeof CommunitiesSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/form/$token': typeof FormTokenRoute
  '/insights/$id': typeof InsightsIdRoute
  '/ticket/$token': typeof TicketTokenRoute
  '/$locale/': typeof LocaleIndexRoute
  '/claim/': typeof ClaimIndexRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/events/': typeof EventsIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/$locale/coach/$profileId': typeof LocaleCoachProfileIdRoute
  '/$locale/communities/$slug': typeof LocaleCommunitiesSlugRoute
  '/$locale/events/$slug': typeof LocaleEventsSlugRoute
  '/$locale/insights/$id': typeof LocaleInsightsIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_staff/articles/$id': typeof StaffArticlesIdRoute
  '/_staff/articles/categories': typeof StaffArticlesCategoriesRoute
  '/_staff/articles/new': typeof StaffArticlesNewRoute
  '/_staff/manage/chat-insights': typeof StaffManageChatInsightsRoute
  '/_staff/manage/europe-pulse': typeof StaffManageEuropePulseRoute
  '/_staff/manage/governance': typeof StaffManageGovernanceRoute
  '/_staff/manage/knowledge': typeof StaffManageKnowledgeRoute
  '/_staff/manage/live-chat': typeof StaffManageLiveChatRoute
  '/_staff/members/$id': typeof StaffMembersIdRoute
  '/api/public/chat-signal': typeof ApiPublicChatSignalRoute
  '/api/public/europe-pulse-scan': typeof ApiPublicEuropePulseScanRoute
  '/api/public/event-reminders': typeof ApiPublicEventRemindersRoute
  '/api/public/live-chat': typeof ApiPublicLiveChatRoute
  '/api/public/live-chat-purge': typeof ApiPublicLiveChatPurgeRoute
  '/api/public/member-sync': typeof ApiPublicMemberSyncRoute
  '/$locale/communities/': typeof LocaleCommunitiesIndexRoute
  '/$locale/events/': typeof LocaleEventsIndexRoute
  '/$locale/insights/': typeof LocaleInsightsIndexRoute
  '/_staff/articles/': typeof StaffArticlesIndexRoute
  '/_staff/members/': typeof StaffMembersIndexRoute
  '/_staff/manage/events/$id': typeof StaffManageEventsIdRoute
  '/api/public/calendar/$file': typeof ApiPublicCalendarFileRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/ticket-qr/$token': typeof ApiPublicTicketQrTokenRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/_staff/manage/events/': typeof StaffManageEventsIndexRoute
  '/_staff/manage/events/$id_/cce': typeof StaffManageEventsIdCceRoute
  '/_staff/manage/events/$id_/check-in': typeof StaffManageEventsIdCheckInRoute
  '/_staff/manage/events/$id_/reporting': typeof StaffManageEventsIdReportingRoute
  '/_staff/manage/events/$id_/forms/$formId': typeof StaffManageEventsIdFormsFormIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/about'
    | '/auth'
    | '/europe-pulse'
    | '/find-a-coach'
    | '/for-coaches'
    | '/for-organisations'
    | '/governance'
    | '/imprint'
    | '/insights'
    | '/mcp'
    | '/no-access'
    | '/privacy'
    | '/sitemap.xml'
    | '/staff-sign-in'
    | '/team'
    | '/$locale/about'
    | '/$locale/europe-pulse'
    | '/$locale/find-a-coach'
    | '/$locale/for-coaches'
    | '/$locale/for-organisations'
    | '/$locale/governance'
    | '/$locale/imprint'
    | '/$locale/insights'
    | '/$locale/privacy'
    | '/$locale/team'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/member'
    | '/my-profile'
    | '/volunteer-chat'
    | '/articles'
    | '/coach-finder'
    | '/integration'
    | '/operational-structure'
    | '/roles'
    | '/vocabularies'
    | '/api/chat'
    | '/auth/callback'
    | '/claim/$token'
    | '/coach/$profileId'
    | '/communities/$slug'
    | '/events/$slug'
    | '/form/$token'
    | '/insights/$id'
    | '/ticket/$token'
    | '/$locale/'
    | '/claim/'
    | '/communities/'
    | '/events/'
    | '/insights/'
    | '/$locale/coach/$profileId'
    | '/$locale/communities/$slug'
    | '/$locale/events/$slug'
    | '/$locale/insights/$id'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/articles/$id'
    | '/articles/categories'
    | '/articles/new'
    | '/manage/chat-insights'
    | '/manage/europe-pulse'
    | '/manage/governance'
    | '/manage/knowledge'
    | '/manage/live-chat'
    | '/members/$id'
    | '/api/public/chat-signal'
    | '/api/public/europe-pulse-scan'
    | '/api/public/event-reminders'
    | '/api/public/live-chat'
    | '/api/public/live-chat-purge'
    | '/api/public/member-sync'
    | '/$locale/communities/'
    | '/$locale/events/'
    | '/$locale/insights/'
    | '/articles/'
    | '/members/'
    | '/manage/events/$id'
    | '/api/public/calendar/$file'
    | '/api/public/payments/webhook'
    | '/api/public/ticket-qr/$token'
    | '/lovable/email/transactional/preview'
    | '/manage/events/'
    | '/manage/events/$id/cce'
    | '/manage/events/$id/check-in'
    | '/manage/events/$id/reporting'
    | '/manage/events/$id/forms/$formId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/europe-pulse'
    | '/find-a-coach'
    | '/for-coaches'
    | '/for-organisations'
    | '/governance'
    | '/imprint'
    | '/mcp'
    | '/no-access'
    | '/privacy'
    | '/sitemap.xml'
    | '/staff-sign-in'
    | '/team'
    | '/$locale/about'
    | '/$locale/europe-pulse'
    | '/$locale/find-a-coach'
    | '/$locale/for-coaches'
    | '/$locale/for-organisations'
    | '/$locale/governance'
    | '/$locale/imprint'
    | '/$locale/privacy'
    | '/$locale/team'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/member'
    | '/my-profile'
    | '/volunteer-chat'
    | '/coach-finder'
    | '/integration'
    | '/operational-structure'
    | '/roles'
    | '/vocabularies'
    | '/api/chat'
    | '/auth/callback'
    | '/claim/$token'
    | '/coach/$profileId'
    | '/communities/$slug'
    | '/events/$slug'
    | '/form/$token'
    | '/insights/$id'
    | '/ticket/$token'
    | '/$locale'
    | '/claim'
    | '/communities'
    | '/events'
    | '/insights'
    | '/$locale/coach/$profileId'
    | '/$locale/communities/$slug'
    | '/$locale/events/$slug'
    | '/$locale/insights/$id'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/articles/$id'
    | '/articles/categories'
    | '/articles/new'
    | '/manage/chat-insights'
    | '/manage/europe-pulse'
    | '/manage/governance'
    | '/manage/knowledge'
    | '/manage/live-chat'
    | '/members/$id'
    | '/api/public/chat-signal'
    | '/api/public/europe-pulse-scan'
    | '/api/public/event-reminders'
    | '/api/public/live-chat'
    | '/api/public/live-chat-purge'
    | '/api/public/member-sync'
    | '/$locale/communities'
    | '/$locale/events'
    | '/$locale/insights'
    | '/articles'
    | '/members'
    | '/manage/events/$id'
    | '/api/public/calendar/$file'
    | '/api/public/payments/webhook'
    | '/api/public/ticket-qr/$token'
    | '/lovable/email/transactional/preview'
    | '/manage/events'
    | '/manage/events/$id/cce'
    | '/manage/events/$id/check-in'
    | '/manage/events/$id/reporting'
    | '/manage/events/$id/forms/$formId'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/_member'
    | '/_staff'
    | '/about'
    | '/auth'
    | '/europe-pulse'
    | '/find-a-coach'
    | '/for-coaches'
    | '/for-organisations'
    | '/governance'
    | '/imprint'
    | '/insights'
    | '/mcp'
    | '/no-access'
    | '/privacy'
    | '/sitemap.xml'
    | '/staff-sign-in'
    | '/team'
    | '/$locale/about'
    | '/$locale/europe-pulse'
    | '/$locale/find-a-coach'
    | '/$locale/for-coaches'
    | '/$locale/for-organisations'
    | '/$locale/governance'
    | '/$locale/imprint'
    | '/$locale/insights'
    | '/$locale/privacy'
    | '/$locale/team'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_member/member'
    | '/_member/my-profile'
    | '/_member/volunteer-chat'
    | '/_staff/articles'
    | '/_staff/coach-finder'
    | '/_staff/integration'
    | '/_staff/operational-structure'
    | '/_staff/roles'
    | '/_staff/vocabularies'
    | '/api/chat'
    | '/auth/callback'
    | '/claim/$token'
    | '/coach/$profileId'
    | '/communities/$slug'
    | '/events/$slug'
    | '/form/$token'
    | '/insights/$id'
    | '/ticket/$token'
    | '/$locale/'
    | '/claim/'
    | '/communities/'
    | '/events/'
    | '/insights/'
    | '/$locale/coach/$profileId'
    | '/$locale/communities/$slug'
    | '/$locale/events/$slug'
    | '/$locale/insights/$id'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_staff/articles/$id'
    | '/_staff/articles/categories'
    | '/_staff/articles/new'
    | '/_staff/manage/chat-insights'
    | '/_staff/manage/europe-pulse'
    | '/_staff/manage/governance'
    | '/_staff/manage/knowledge'
    | '/_staff/manage/live-chat'
    | '/_staff/members/$id'
    | '/api/public/chat-signal'
    | '/api/public/europe-pulse-scan'
    | '/api/public/event-reminders'
    | '/api/public/live-chat'
    | '/api/public/live-chat-purge'
    | '/api/public/member-sync'
    | '/$locale/communities/'
    | '/$locale/events/'
    | '/$locale/insights/'
    | '/_staff/articles/'
    | '/_staff/members/'
    | '/_staff/manage/events/$id'
    | '/api/public/calendar/$file'
    | '/api/public/payments/webhook'
    | '/api/public/ticket-qr/$token'
    | '/lovable/email/transactional/preview'
    | '/_staff/manage/events/'
    | '/_staff/manage/events/$id_/cce'
    | '/_staff/manage/events/$id_/check-in'
    | '/_staff/manage/events/$id_/reporting'
    | '/_staff/manage/events/$id_/forms/$formId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
  MemberRouteRoute: typeof MemberRouteRouteWithChildren
  StaffRouteRoute: typeof StaffRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  EuropePulseRoute: typeof EuropePulseRoute
  FindACoachRoute: typeof FindACoachRoute
  ForCoachesRoute: typeof ForCoachesRoute
  ForOrganisationsRoute: typeof ForOrganisationsRoute
  GovernanceRoute: typeof GovernanceRoute
  ImprintRoute: typeof ImprintRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  McpRoute: typeof McpRoute
  NoAccessRoute: typeof NoAccessRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StaffSignInRoute: typeof StaffSignInRoute
  TeamRoute: typeof TeamRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  ClaimTokenRoute: typeof ClaimTokenRoute
  CoachProfileIdRoute: typeof CoachProfileIdRoute
  CommunitiesSlugRoute: typeof CommunitiesSlugRoute
  EventsSlugRoute: typeof EventsSlugRoute
  FormTokenRoute: typeof FormTokenRoute
  TicketTokenRoute: typeof TicketTokenRoute
  ClaimIndexRoute: typeof ClaimIndexRoute
  CommunitiesIndexRoute: typeof CommunitiesIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicChatSignalRoute: typeof ApiPublicChatSignalRoute
  ApiPublicEuropePulseScanRoute: typeof ApiPublicEuropePulseScanRoute
  ApiPublicEventRemindersRoute: typeof ApiPublicEventRemindersRoute
  ApiPublicLiveChatRoute: typeof ApiPublicLiveChatRoute
  ApiPublicLiveChatPurgeRoute: typeof ApiPublicLiveChatPurgeRoute
  ApiPublicMemberSyncRoute: typeof ApiPublicMemberSyncRoute
  ApiPublicCalendarFileRoute: typeof ApiPublicCalendarFileRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicTicketQrTokenRoute: typeof ApiPublicTicketQrTokenRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_member': {
      id: '/_member'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MemberRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff': {
      id: '/_staff'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StaffRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/europe-pulse': {
      id: '/europe-pulse'
      path: '/europe-pulse'
      fullPath: '/europe-pulse'
      preLoaderRoute: typeof EuropePulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-a-coach': {
      id: '/find-a-coach'
      path: '/find-a-coach'
      fullPath: '/find-a-coach'
      preLoaderRoute: typeof FindACoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-coaches': {
      id: '/for-coaches'
      path: '/for-coaches'
      fullPath: '/for-coaches'
      preLoaderRoute: typeof ForCoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-organisations': {
      id: '/for-organisations'
      path: '/for-organisations'
      fullPath: '/for-organisations'
      preLoaderRoute: typeof ForOrganisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-sign-in': {
      id: '/staff-sign-in'
      path: '/staff-sign-in'
      fullPath: '/staff-sign-in'
      preLoaderRoute: typeof StaffSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/europe-pulse': {
      id: '/$locale/europe-pulse'
      path: '/europe-pulse'
      fullPath: '/$locale/europe-pulse'
      preLoaderRoute: typeof LocaleEuropePulseRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/find-a-coach': {
      id: '/$locale/find-a-coach'
      path: '/find-a-coach'
      fullPath: '/$locale/find-a-coach'
      preLoaderRoute: typeof LocaleFindACoachRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/for-coaches': {
      id: '/$locale/for-coaches'
      path: '/for-coaches'
      fullPath: '/$locale/for-coaches'
      preLoaderRoute: typeof LocaleForCoachesRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/for-organisations': {
      id: '/$locale/for-organisations'
      path: '/for-organisations'
      fullPath: '/$locale/for-organisations'
      preLoaderRoute: typeof LocaleForOrganisationsRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/governance': {
      id: '/$locale/governance'
      path: '/governance'
      fullPath: '/$locale/governance'
      preLoaderRoute: typeof LocaleGovernanceRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/imprint': {
      id: '/$locale/imprint'
      path: '/imprint'
      fullPath: '/$locale/imprint'
      preLoaderRoute: typeof LocaleImprintRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/insights': {
      id: '/$locale/insights'
      path: '/insights'
      fullPath: '/$locale/insights'
      preLoaderRoute: typeof LocaleInsightsRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/privacy': {
      id: '/$locale/privacy'
      path: '/privacy'
      fullPath: '/$locale/privacy'
      preLoaderRoute: typeof LocalePrivacyRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/team': {
      id: '/$locale/team'
      path: '/team'
      fullPath: '/$locale/team'
      preLoaderRoute: typeof LocaleTeamRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_member/member': {
      id: '/_member/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberMemberRouteImport
      parentRoute: typeof MemberRouteRoute
    }
    '/_member/my-profile': {
      id: '/_member/my-profile'
      path: '/my-profile'
      fullPath: '/my-profile'
      preLoaderRoute: typeof MemberMyProfileRouteImport
      parentRoute: typeof MemberRouteRoute
    }
    '/_member/volunteer-chat': {
      id: '/_member/volunteer-chat'
      path: '/volunteer-chat'
      fullPath: '/volunteer-chat'
      preLoaderRoute: typeof MemberVolunteerChatRouteImport
      parentRoute: typeof MemberRouteRoute
    }
    '/_staff/articles': {
      id: '/_staff/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof StaffArticlesRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/coach-finder': {
      id: '/_staff/coach-finder'
      path: '/coach-finder'
      fullPath: '/coach-finder'
      preLoaderRoute: typeof StaffCoachFinderRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/integration': {
      id: '/_staff/integration'
      path: '/integration'
      fullPath: '/integration'
      preLoaderRoute: typeof StaffIntegrationRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/operational-structure': {
      id: '/_staff/operational-structure'
      path: '/operational-structure'
      fullPath: '/operational-structure'
      preLoaderRoute: typeof StaffOperationalStructureRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/roles': {
      id: '/_staff/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof StaffRolesRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/vocabularies': {
      id: '/_staff/vocabularies'
      path: '/vocabularies'
      fullPath: '/vocabularies'
      preLoaderRoute: typeof StaffVocabulariesRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/claim/': {
      id: '/claim/'
      path: '/claim'
      fullPath: '/claim/'
      preLoaderRoute: typeof ClaimIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$token': {
      id: '/claim/$token'
      path: '/claim/$token'
      fullPath: '/claim/$token'
      preLoaderRoute: typeof ClaimTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/$profileId': {
      id: '/coach/$profileId'
      path: '/coach/$profileId'
      fullPath: '/coach/$profileId'
      preLoaderRoute: typeof CoachProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/': {
      id: '/communities/'
      path: '/communities'
      fullPath: '/communities/'
      preLoaderRoute: typeof CommunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/$slug': {
      id: '/communities/$slug'
      path: '/communities/$slug'
      fullPath: '/communities/$slug'
      preLoaderRoute: typeof CommunitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form/$token': {
      id: '/form/$token'
      path: '/form/$token'
      fullPath: '/form/$token'
      preLoaderRoute: typeof FormTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/insights/$id': {
      id: '/insights/$id'
      path: '/$id'
      fullPath: '/insights/$id'
      preLoaderRoute: typeof InsightsIdRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/ticket/$token': {
      id: '/ticket/$token'
      path: '/ticket/$token'
      fullPath: '/ticket/$token'
      preLoaderRoute: typeof TicketTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/coach/$profileId': {
      id: '/$locale/coach/$profileId'
      path: '/coach/$profileId'
      fullPath: '/$locale/coach/$profileId'
      preLoaderRoute: typeof LocaleCoachProfileIdRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/communities/': {
      id: '/$locale/communities/'
      path: '/communities'
      fullPath: '/$locale/communities/'
      preLoaderRoute: typeof LocaleCommunitiesIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/communities/$slug': {
      id: '/$locale/communities/$slug'
      path: '/communities/$slug'
      fullPath: '/$locale/communities/$slug'
      preLoaderRoute: typeof LocaleCommunitiesSlugRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/events/': {
      id: '/$locale/events/'
      path: '/events'
      fullPath: '/$locale/events/'
      preLoaderRoute: typeof LocaleEventsIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/events/$slug': {
      id: '/$locale/events/$slug'
      path: '/events/$slug'
      fullPath: '/$locale/events/$slug'
      preLoaderRoute: typeof LocaleEventsSlugRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/insights/': {
      id: '/$locale/insights/'
      path: '/'
      fullPath: '/$locale/insights/'
      preLoaderRoute: typeof LocaleInsightsIndexRouteImport
      parentRoute: typeof LocaleInsightsRoute
    }
    '/$locale/insights/$id': {
      id: '/$locale/insights/$id'
      path: '/$id'
      fullPath: '/$locale/insights/$id'
      preLoaderRoute: typeof LocaleInsightsIdRouteImport
      parentRoute: typeof LocaleInsightsRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff/articles/': {
      id: '/_staff/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof StaffArticlesIndexRouteImport
      parentRoute: typeof StaffArticlesRoute
    }
    '/_staff/articles/$id': {
      id: '/_staff/articles/$id'
      path: '/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof StaffArticlesIdRouteImport
      parentRoute: typeof StaffArticlesRoute
    }
    '/_staff/articles/categories': {
      id: '/_staff/articles/categories'
      path: '/categories'
      fullPath: '/articles/categories'
      preLoaderRoute: typeof StaffArticlesCategoriesRouteImport
      parentRoute: typeof StaffArticlesRoute
    }
    '/_staff/articles/new': {
      id: '/_staff/articles/new'
      path: '/new'
      fullPath: '/articles/new'
      preLoaderRoute: typeof StaffArticlesNewRouteImport
      parentRoute: typeof StaffArticlesRoute
    }
    '/_staff/manage/chat-insights': {
      id: '/_staff/manage/chat-insights'
      path: '/manage/chat-insights'
      fullPath: '/manage/chat-insights'
      preLoaderRoute: typeof StaffManageChatInsightsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/manage/europe-pulse': {
      id: '/_staff/manage/europe-pulse'
      path: '/manage/europe-pulse'
      fullPath: '/manage/europe-pulse'
      preLoaderRoute: typeof StaffManageEuropePulseRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/manage/governance': {
      id: '/_staff/manage/governance'
      path: '/manage/governance'
      fullPath: '/manage/governance'
      preLoaderRoute: typeof StaffManageGovernanceRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/manage/knowledge': {
      id: '/_staff/manage/knowledge'
      path: '/manage/knowledge'
      fullPath: '/manage/knowledge'
      preLoaderRoute: typeof StaffManageKnowledgeRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/manage/live-chat': {
      id: '/_staff/manage/live-chat'
      path: '/manage/live-chat'
      fullPath: '/manage/live-chat'
      preLoaderRoute: typeof StaffManageLiveChatRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/members/': {
      id: '/_staff/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof StaffMembersIndexRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/members/$id': {
      id: '/_staff/members/$id'
      path: '/members/$id'
      fullPath: '/members/$id'
      preLoaderRoute: typeof StaffMembersIdRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/api/public/chat-signal': {
      id: '/api/public/chat-signal'
      path: '/api/public/chat-signal'
      fullPath: '/api/public/chat-signal'
      preLoaderRoute: typeof ApiPublicChatSignalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/europe-pulse-scan': {
      id: '/api/public/europe-pulse-scan'
      path: '/api/public/europe-pulse-scan'
      fullPath: '/api/public/europe-pulse-scan'
      preLoaderRoute: typeof ApiPublicEuropePulseScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/event-reminders': {
      id: '/api/public/event-reminders'
      path: '/api/public/event-reminders'
      fullPath: '/api/public/event-reminders'
      preLoaderRoute: typeof ApiPublicEventRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/live-chat': {
      id: '/api/public/live-chat'
      path: '/api/public/live-chat'
      fullPath: '/api/public/live-chat'
      preLoaderRoute: typeof ApiPublicLiveChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/live-chat-purge': {
      id: '/api/public/live-chat-purge'
      path: '/api/public/live-chat-purge'
      fullPath: '/api/public/live-chat-purge'
      preLoaderRoute: typeof ApiPublicLiveChatPurgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/member-sync': {
      id: '/api/public/member-sync'
      path: '/api/public/member-sync'
      fullPath: '/api/public/member-sync'
      preLoaderRoute: typeof ApiPublicMemberSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff/manage/events/': {
      id: '/_staff/manage/events/'
      path: '/manage/events'
      fullPath: '/manage/events/'
      preLoaderRoute: typeof StaffManageEventsIndexRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/manage/events/$id': {
      id: '/_staff/manage/events/$id'
      path: '/manage/events/$id'
      fullPath: '/manage/events/$id'
      preLoaderRoute: typeof StaffManageEventsIdRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/api/public/calendar/$file': {
      id: '/api/public/calendar/$file'
      path: '/api/public/calendar/$file'
      fullPath: '/api/public/calendar/$file'
      preLoaderRoute: typeof ApiPublicCalendarFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ticket-qr/$token': {
      id: '/api/public/ticket-qr/$token'
      path: '/api/public/ticket-qr/$token'
      fullPath: '/api/public/ticket-qr/$token'
      preLoaderRoute: typeof ApiPublicTicketQrTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff/manage/events/$id_/cce': {
      id: '/_staff/manage/events/$id_/cce'
      path: '/manage/events/$id/cce'
      fullPath: '/manage/events/$id/cce'
      preLoaderRoute: typeof StaffManageEventsIdCceRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/manage/events/$id_/check-in': {
      id: '/_staff/manage/events/$id_/check-in'
      path: '/manage/events/$id/check-in'
      fullPath: '/manage/events/$id/check-in'
      preLoaderRoute: typeof StaffManageEventsIdCheckInRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/manage/events/$id_/reporting': {
      id: '/_staff/manage/events/$id_/reporting'
      path: '/manage/events/$id/reporting'
      fullPath: '/manage/events/$id/reporting'
      preLoaderRoute: typeof StaffManageEventsIdReportingRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/manage/events/$id_/forms/$formId': {
      id: '/_staff/manage/events/$id_/forms/$formId'
      path: '/manage/events/$id/forms/$formId'
      fullPath: '/manage/events/$id/forms/$formId'
      preLoaderRoute: typeof StaffManageEventsIdFormsFormIdRouteImport
      parentRoute: typeof StaffRouteRoute
    }
  }
}

interface LocaleInsightsRouteChildren {
  LocaleInsightsIdRoute: typeof LocaleInsightsIdRoute
  LocaleInsightsIndexRoute: typeof LocaleInsightsIndexRoute
}

const LocaleInsightsRouteChildren: LocaleInsightsRouteChildren = {
  LocaleInsightsIdRoute: LocaleInsightsIdRoute,
  LocaleInsightsIndexRoute: LocaleInsightsIndexRoute,
}

const LocaleInsightsRouteWithChildren = LocaleInsightsRoute._addFileChildren(
  LocaleInsightsRouteChildren,
)

interface LocaleRouteRouteChildren {
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleEuropePulseRoute: typeof LocaleEuropePulseRoute
  LocaleFindACoachRoute: typeof LocaleFindACoachRoute
  LocaleForCoachesRoute: typeof LocaleForCoachesRoute
  LocaleForOrganisationsRoute: typeof LocaleForOrganisationsRoute
  LocaleGovernanceRoute: typeof LocaleGovernanceRoute
  LocaleImprintRoute: typeof LocaleImprintRoute
  LocaleInsightsRoute: typeof LocaleInsightsRouteWithChildren
  LocalePrivacyRoute: typeof LocalePrivacyRoute
  LocaleTeamRoute: typeof LocaleTeamRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleCoachProfileIdRoute: typeof LocaleCoachProfileIdRoute
  LocaleCommunitiesSlugRoute: typeof LocaleCommunitiesSlugRoute
  LocaleEventsSlugRoute: typeof LocaleEventsSlugRoute
  LocaleCommunitiesIndexRoute: typeof LocaleCommunitiesIndexRoute
  LocaleEventsIndexRoute: typeof LocaleEventsIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleEuropePulseRoute: LocaleEuropePulseRoute,
  LocaleFindACoachRoute: LocaleFindACoachRoute,
  LocaleForCoachesRoute: LocaleForCoachesRoute,
  LocaleForOrganisationsRoute: LocaleForOrganisationsRoute,
  LocaleGovernanceRoute: LocaleGovernanceRoute,
  LocaleImprintRoute: LocaleImprintRoute,
  LocaleInsightsRoute: LocaleInsightsRouteWithChildren,
  LocalePrivacyRoute: LocalePrivacyRoute,
  LocaleTeamRoute: LocaleTeamRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleCoachProfileIdRoute: LocaleCoachProfileIdRoute,
  LocaleCommunitiesSlugRoute: LocaleCommunitiesSlugRoute,
  LocaleEventsSlugRoute: LocaleEventsSlugRoute,
  LocaleCommunitiesIndexRoute: LocaleCommunitiesIndexRoute,
  LocaleEventsIndexRoute: LocaleEventsIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

interface MemberRouteRouteChildren {
  MemberMemberRoute: typeof MemberMemberRoute
  MemberMyProfileRoute: typeof MemberMyProfileRoute
  MemberVolunteerChatRoute: typeof MemberVolunteerChatRoute
}

const MemberRouteRouteChildren: MemberRouteRouteChildren = {
  MemberMemberRoute: MemberMemberRoute,
  MemberMyProfileRoute: MemberMyProfileRoute,
  MemberVolunteerChatRoute: MemberVolunteerChatRoute,
}

const MemberRouteRouteWithChildren = MemberRouteRoute._addFileChildren(
  MemberRouteRouteChildren,
)

interface StaffArticlesRouteChildren {
  StaffArticlesIdRoute: typeof StaffArticlesIdRoute
  StaffArticlesCategoriesRoute: typeof StaffArticlesCategoriesRoute
  StaffArticlesNewRoute: typeof StaffArticlesNewRoute
  StaffArticlesIndexRoute: typeof StaffArticlesIndexRoute
}

const StaffArticlesRouteChildren: StaffArticlesRouteChildren = {
  StaffArticlesIdRoute: StaffArticlesIdRoute,
  StaffArticlesCategoriesRoute: StaffArticlesCategoriesRoute,
  StaffArticlesNewRoute: StaffArticlesNewRoute,
  StaffArticlesIndexRoute: StaffArticlesIndexRoute,
}

const StaffArticlesRouteWithChildren = StaffArticlesRoute._addFileChildren(
  StaffArticlesRouteChildren,
)

interface StaffRouteRouteChildren {
  StaffArticlesRoute: typeof StaffArticlesRouteWithChildren
  StaffCoachFinderRoute: typeof StaffCoachFinderRoute
  StaffIntegrationRoute: typeof StaffIntegrationRoute
  StaffOperationalStructureRoute: typeof StaffOperationalStructureRoute
  StaffRolesRoute: typeof StaffRolesRoute
  StaffVocabulariesRoute: typeof StaffVocabulariesRoute
  StaffManageChatInsightsRoute: typeof StaffManageChatInsightsRoute
  StaffManageEuropePulseRoute: typeof StaffManageEuropePulseRoute
  StaffManageGovernanceRoute: typeof StaffManageGovernanceRoute
  StaffManageKnowledgeRoute: typeof StaffManageKnowledgeRoute
  StaffManageLiveChatRoute: typeof StaffManageLiveChatRoute
  StaffMembersIdRoute: typeof StaffMembersIdRoute
  StaffMembersIndexRoute: typeof StaffMembersIndexRoute
  StaffManageEventsIdRoute: typeof StaffManageEventsIdRoute
  StaffManageEventsIndexRoute: typeof StaffManageEventsIndexRoute
  StaffManageEventsIdCceRoute: typeof StaffManageEventsIdCceRoute
  StaffManageEventsIdCheckInRoute: typeof StaffManageEventsIdCheckInRoute
  StaffManageEventsIdReportingRoute: typeof StaffManageEventsIdReportingRoute
  StaffManageEventsIdFormsFormIdRoute: typeof StaffManageEventsIdFormsFormIdRoute
}

const StaffRouteRouteChildren: StaffRouteRouteChildren = {
  StaffArticlesRoute: StaffArticlesRouteWithChildren,
  StaffCoachFinderRoute: StaffCoachFinderRoute,
  StaffIntegrationRoute: StaffIntegrationRoute,
  StaffOperationalStructureRoute: StaffOperationalStructureRoute,
  StaffRolesRoute: StaffRolesRoute,
  StaffVocabulariesRoute: StaffVocabulariesRoute,
  StaffManageChatInsightsRoute: StaffManageChatInsightsRoute,
  StaffManageEuropePulseRoute: StaffManageEuropePulseRoute,
  StaffManageGovernanceRoute: StaffManageGovernanceRoute,
  StaffManageKnowledgeRoute: StaffManageKnowledgeRoute,
  StaffManageLiveChatRoute: StaffManageLiveChatRoute,
  StaffMembersIdRoute: StaffMembersIdRoute,
  StaffMembersIndexRoute: StaffMembersIndexRoute,
  StaffManageEventsIdRoute: StaffManageEventsIdRoute,
  StaffManageEventsIndexRoute: StaffManageEventsIndexRoute,
  StaffManageEventsIdCceRoute: StaffManageEventsIdCceRoute,
  StaffManageEventsIdCheckInRoute: StaffManageEventsIdCheckInRoute,
  StaffManageEventsIdReportingRoute: StaffManageEventsIdReportingRoute,
  StaffManageEventsIdFormsFormIdRoute: StaffManageEventsIdFormsFormIdRoute,
}

const StaffRouteRouteWithChildren = StaffRouteRoute._addFileChildren(
  StaffRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface InsightsRouteChildren {
  InsightsIdRoute: typeof InsightsIdRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsIdRoute: InsightsIdRoute,
  InsightsIndexRoute: InsightsIndexRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
  MemberRouteRoute: MemberRouteRouteWithChildren,
  StaffRouteRoute: StaffRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  EuropePulseRoute: EuropePulseRoute,
  FindACoachRoute: FindACoachRoute,
  ForCoachesRoute: ForCoachesRoute,
  ForOrganisationsRoute: ForOrganisationsRoute,
  GovernanceRoute: GovernanceRoute,
  ImprintRoute: ImprintRoute,
  InsightsRoute: InsightsRouteWithChildren,
  McpRoute: McpRoute,
  NoAccessRoute: NoAccessRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StaffSignInRoute: StaffSignInRoute,
  TeamRoute: TeamRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  ClaimTokenRoute: ClaimTokenRoute,
  CoachProfileIdRoute: CoachProfileIdRoute,
  CommunitiesSlugRoute: CommunitiesSlugRoute,
  EventsSlugRoute: EventsSlugRoute,
  FormTokenRoute: FormTokenRoute,
  TicketTokenRoute: TicketTokenRoute,
  ClaimIndexRoute: ClaimIndexRoute,
  CommunitiesIndexRoute: CommunitiesIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicChatSignalRoute: ApiPublicChatSignalRoute,
  ApiPublicEuropePulseScanRoute: ApiPublicEuropePulseScanRoute,
  ApiPublicEventRemindersRoute: ApiPublicEventRemindersRoute,
  ApiPublicLiveChatRoute: ApiPublicLiveChatRoute,
  ApiPublicLiveChatPurgeRoute: ApiPublicLiveChatPurgeRoute,
  ApiPublicMemberSyncRoute: ApiPublicMemberSyncRoute,
  ApiPublicCalendarFileRoute: ApiPublicCalendarFileRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicTicketQrTokenRoute: ApiPublicTicketQrTokenRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
